spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: bloghub-service
          uri: loadbalancer://bloghub-service
          predicates:
            - Path=/api/v1/users, /api/v1/blogs

        - id: bloghub-email-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/emails

        - id: bloghub-payment-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/payments

server:
  port: 9090

